name: OrderFlow CI

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "OrderFlow@123"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'OrderFlow@123' -Q 'SELECT 1' -C"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --health-start-period 20s

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 10s

    env:
      Redis__ConnectionString: localhost:6379,abortConnect=false
      Redis__OrderCacheExpirationMinutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore OrderFlow.slnx

      - name: Build solution
        run: dotnet build OrderFlow.slnx --configuration Release --no-restore

      - name: Run tests with coverage
        run: dotnet test OrderFlow.slnx --configuration Release --no-build --collect:"XPlat Code Coverage"