name: OrderFlow CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore OrderFlow.sln

      - name: Build solution
        run: dotnet build OrderFlow.sln --configuration Release --no-restore